[CI] Work around python-mfusepy test error

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -104,8 +104,7 @@ jobs:
           su user -c "git commit -m 'Update to $pkgver'"
           su user -c 'git show | cat'
 
-      - name: Test PKGBUILD
-        if: startsWith(github.ref, 'refs/tags/v')
+      - name: Install pikaur
         run: |
           # makepkgs does not work because the PKGBUILD depends on other AUR packages.
           #su user -c 'makepkg -s --noconfirm'
@@ -115,12 +114,23 @@ jobs:
           #su user -c 'git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm'
           #su user -c 'yay -Bi --noconfirm .'
           su user -c 'git clone https://aur.archlinux.org/pikaur.git && cd pikaur && makepkg -fsri --noconfirm'
-          su user -c 'pikaur -P --noconfirm'
-          su user -c 'pikaur -Pi --noconfirm ./PKGBUILD'
+
+      - name: Install Optional Dependencies
+        run: |
           # python3-s3fs won't install because of fsspec version conflict -.-
           # python-s3fs depends on: 'python-fsspec=2024.6.1'
           # found in 'PackageSource.REPO': '2024.10.0-1'
+          # Tests for mfusepy fail because FUSE does not work inside Docker without privileges.
+          su user -c 'pikaur --noconfirm --asdeps -Sy python-mfusepy' || true
           su user -c 'pikaur --noconfirm --asdeps -Sy python-fsspec python-aiohttp python-requests'
+
+      - name: Build and Install PKGBUILD
+        run: |
+          su user -c 'pikaur -P --noconfirm'
+          su user -c 'pikaur -Pi --noconfirm ./PKGBUILD'
+
+      - name: Test Installed Ratarmount
+        run: |
           su user -c 'python3 -c "import sys; from ratarmountcore.mountsource.factory import open_mount_source as oms; files = oms(sys.argv[1], printDebug=3).list(\"\"); print(files); assert files" *.tar.gz'
           su user -c 'python3 -c "from ratarmountcore.mountsource.factory import open_mount_source as oms; files = oms(\"https://raw.githubusercontent.com/mxmlnkn/ratarmount/refs/heads/master/tests/single-file.tar\", printDebug=3).list(\"\"); print(files); assert files"'
 
